### PR TITLE
Added method on PLDA model to perform similarity

### PR DESCRIPTION
**Pull request by seandickert**
Similarity score between two sets of utterances, possibly from speakers not in the training set

### CODE REVIEW

**Comment by seandickert** [comment]
Will do, will update soon

**Comment by seandickert** [comment]
Made the changes. Sorry, didn't respond to the first question before, but yes, it's working for me.

**Comment by RaviSoji** [comment]
Hey, sorry I've been swamped with school and work. I'll have a chance this weekend to merge.

Thanks again!!

**Comment by RaviSoji** [comment]
Hey, apologies for the delay. I went ahead and just merged it since it looks good and it's working for you.

Thanks again for doing this!

**Pull request merged**
